package protocol

import (
	"regexp"
	"unicode/utf8"
)

// Node pairing and connection are the only HTTP surfaces a node uses before the Bridge
// WebSocket is established. Both paths are relative to the Nexus endpoint the node was
// configured with; a node never discovers or selects anything beyond that endpoint.
const (
	// PairPath accepts POST with a JSON PairRequest and answers 201 Created with a PairResponse.
	// Any other status means pairing failed; the error body is implementation specific.
	PairPath = "/v1/nodes/pair"
	// ConnectPath is the WebSocket upgrade endpoint (ws/wss matching the endpoint scheme).
	// The upgrade request carries "Authorization: Bearer <device_token>". After the upgrade the
	// node sends MessageNodeHello first and the server answers MessageNodeReady.
	ConnectPath = "/v1/nodes/connect"
)

const (
	// MaxNodeNameRunes bounds PairRequest.Name after trimming surrounding whitespace.
	MaxNodeNameRunes = 100
)

var deviceIDPattern = regexp.MustCompile(`^[A-Za-z0-9][A-Za-z0-9._-]{7,127}$`)

// PairRequest exchanges a short-lived single-use pairing code for a device token.
//
// DeviceID is generated by the node for every pairing and must satisfy ValidDeviceID.
// The same DeviceID is later sent in Hello.DeviceID, and servers reject a connection whose
// Hello.DeviceID differs from the DeviceID recorded at pairing.
type PairRequest struct {
	Code     string `json:"code"`
	DeviceID string `json:"device_id"`
	Name     string `json:"name"`
}

// PairResponse is the 201 Created body of PairPath.
// Servers may add fields; nodes must ignore fields they do not know.
type PairResponse struct {
	Node        PairedNode `json:"node"`
	DeviceToken string     `json:"device_token"`
}

// PairedNode identifies the node record created by pairing.
type PairedNode struct {
	ID string `json:"id"`
}

// ValidDeviceID reports whether a node-generated device ID is acceptable on the wire.
func ValidDeviceID(deviceID string) bool {
	return deviceIDPattern.MatchString(deviceID)
}

// ValidNodeName reports whether a trimmed node display name is acceptable on the wire.
func ValidNodeName(name string) bool {
	count := utf8.RuneCountInString(name)
	return count >= 1 && count <= MaxNodeNameRunes
}
