// Package runtimecontractv1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package runtimecontractv1

// JSONObject defines model for JSONObject.
type JSONObject map[string]interface{}

// MCPDetailResponse defines model for MCPDetailResponse.
type MCPDetailResponse struct {
	Action string           `json:"action"`
	Config MCPServerConfig  `json:"config"`
	Ok     bool             `json:"ok"`
	Server MCPServerSummary `json:"server"`
	Source string           `json:"source"`
}

// MCPListResponse defines model for MCPListResponse.
type MCPListResponse struct {
	Action  string             `json:"action"`
	Count   int                `json:"count"`
	Ok      bool               `json:"ok"`
	Servers []MCPServerSummary `json:"servers"`
	Source  string             `json:"source"`
}

// MCPServerConfig defines model for MCPServerConfig.
type MCPServerConfig struct {
	Args        []string          `json:"args,omitempty,omitzero"`
	Command     string            `json:"command,omitempty,omitzero"`
	Cwd         string            `json:"cwd,omitempty,omitzero"`
	Description string            `json:"description"`
	Enabled     bool              `json:"enabled"`
	EnvFromEnv  map[string]string `json:"env_from_env,omitempty,omitzero"`
	HeaderEnv   map[string]string `json:"header_env,omitempty,omitzero"`
	Name        string            `json:"name"`
	TimeoutMS   int               `json:"timeout_ms,omitempty,omitzero"`
	Transport   string            `json:"transport"`
	URL         string            `json:"url,omitempty,omitzero"`
}

// MCPServerSummary defines model for MCPServerSummary.
type MCPServerSummary struct {
	Description   string `json:"description"`
	DisplayName   string `json:"display_name,omitempty,omitzero"`
	Enabled       bool   `json:"enabled"`
	LastError     string `json:"last_error,omitempty,omitzero"`
	LastErrorCode string `json:"last_error_code,omitempty,omitzero"`
	Name          string `json:"name"`
	PluginName    string `json:"plugin_name,omitempty,omitzero"`
	RefreshedAt   string `json:"refreshed_at,omitempty,omitzero"`
	SourceType    string `json:"source_type"`
	Status        string `json:"status"`
	ToolCount     int    `json:"tool_count"`
	Transport     string `json:"transport"`
}

// PluginDetail defines model for PluginDetail.
type PluginDetail struct {
	Description   string            `json:"description,omitempty,omitzero"`
	Enabled       bool              `json:"enabled"`
	Executables   []string          `json:"executables"`
	Format        string            `json:"format"`
	InstalledAt   string            `json:"installed_at"`
	MCP           []PluginMCP       `json:"mcp"`
	Name          string            `json:"name"`
	PackageDigest string            `json:"package_digest"`
	Provenance    *PluginProvenance `json:"provenance,omitempty"`
	Skills        []PluginSkill     `json:"skills"`
	Version       string            `json:"version"`
	Warnings      []string          `json:"warnings"`
}

// PluginDetailResponse defines model for PluginDetailResponse.
type PluginDetailResponse struct {
	Action        string       `json:"action,omitempty,omitzero"`
	Enabled       bool         `json:"enabled,omitempty,omitzero"`
	Name          string       `json:"name,omitempty,omitzero"`
	Ok            bool         `json:"ok"`
	PackageDigest string       `json:"package_digest,omitempty,omitzero"`
	Plugin        PluginDetail `json:"plugin"`
	Source        string       `json:"source"`
	Version       string       `json:"version,omitempty,omitzero"`
}

// PluginListResponse defines model for PluginListResponse.
type PluginListResponse struct {
	Count   int             `json:"count"`
	Ok      bool            `json:"ok"`
	Plugins []PluginSummary `json:"plugins"`
	Source  string          `json:"source"`
}

// PluginMCP defines model for PluginMCP.
type PluginMCP struct {
	Command     string `json:"command,omitempty,omitzero"`
	Cwd         string `json:"cwd,omitempty,omitzero"`
	Description string `json:"description,omitempty,omitzero"`
	Name        string `json:"name"`
	RuntimeName string `json:"runtime_name,omitempty,omitzero"`
	Transport   string `json:"transport"`
	URL         string `json:"url,omitempty,omitzero"`
}

// PluginProvenance defines model for PluginProvenance.
type PluginProvenance struct {
	Origin   string `json:"origin"`
	Ref      string `json:"ref,omitempty,omitzero"`
	Revision string `json:"revision,omitempty,omitzero"`
	Subdir   string `json:"subdir,omitempty,omitzero"`
}

// PluginSkill defines model for PluginSkill.
type PluginSkill struct {
	ContentDigest string `json:"content_digest"`
	Description   string `json:"description,omitempty,omitzero"`
	Name          string `json:"name"`
	Path          string `json:"path"`
}

// PluginSummary defines model for PluginSummary.
type PluginSummary struct {
	Enabled       bool              `json:"enabled"`
	Format        string            `json:"format"`
	MCPCount      int               `json:"mcp_count"`
	Name          string            `json:"name"`
	PackageDigest string            `json:"package_digest"`
	Provenance    *PluginProvenance `json:"provenance,omitempty"`
	SkillCount    int               `json:"skill_count"`
	Version       string            `json:"version"`
}

// SkillDetailResponse defines model for SkillDetailResponse.
type SkillDetailResponse struct {
	Action        string      `json:"action"`
	ContentDigest string      `json:"content_digest"`
	Description   string      `json:"description"`
	Document      JSONObject  `json:"document"`
	FileCount     int         `json:"file_count"`
	Files         []SkillFile `json:"files"`
	Name          string      `json:"name"`
	PluginName    string      `json:"plugin_name,omitempty,omitzero"`
	Skill         string      `json:"skill"`
	SkillRef      string      `json:"skill_ref"`
	Source        string      `json:"source"`
	SourceType    string      `json:"source_type"`
}

// SkillFile defines model for SkillFile.
type SkillFile struct {
	Kind      string `json:"kind"`
	Path      string `json:"path"`
	SizeBytes int64  `json:"size_bytes"`
	UpdatedAt string `json:"updated_at"`
}

// SkillFileContent defines model for SkillFileContent.
type SkillFileContent struct {
	Content   string `json:"content"`
	Kind      string `json:"kind"`
	Path      string `json:"path"`
	SizeBytes int64  `json:"size_bytes"`
	Truncated bool   `json:"truncated"`
	UpdatedAt string `json:"updated_at"`
}

// SkillFileResponse defines model for SkillFileResponse.
type SkillFileResponse struct {
	Action        string           `json:"action"`
	ContentDigest string           `json:"content_digest"`
	File          SkillFileContent `json:"file"`
	Skill         string           `json:"skill"`
	SkillRef      string           `json:"skill_ref"`
	Source        string           `json:"source"`
}

// SkillFilesResponse defines model for SkillFilesResponse.
type SkillFilesResponse struct {
	Action        string      `json:"action"`
	ContentDigest string      `json:"content_digest"`
	Count         int         `json:"count"`
	Files         []SkillFile `json:"files"`
	Skill         string      `json:"skill"`
	SkillRef      string      `json:"skill_ref"`
	Source        string      `json:"source"`
}

// SkillListResponse defines model for SkillListResponse.
type SkillListResponse struct {
	Action string         `json:"action"`
	Count  int            `json:"count"`
	Skills []SkillSummary `json:"skills"`
	Source string         `json:"source"`
}

// SkillSummary defines model for SkillSummary.
type SkillSummary struct {
	ContentDigest string `json:"content_digest"`
	Description   string `json:"description"`
	FileCount     int    `json:"file_count"`
	Name          string `json:"name"`
	PluginName    string `json:"plugin_name,omitempty,omitzero"`
	Skill         string `json:"skill"`
	SkillRef      string `json:"skill_ref"`
	SourceType    string `json:"source_type"`
}

// StatusResponse defines model for StatusResponse.
type StatusResponse struct {
	AgentDockDefaultDir    string   `json:"agentdock_default_dir,omitempty,omitzero"`
	AgentDockHome          string   `json:"agentdock_home,omitempty,omitzero"`
	AuthEnabled            bool     `json:"auth_enabled,omitempty,omitzero"`
	BrowserEnabled         bool     `json:"browser_enabled,omitempty,omitzero"`
	MemoryEnabled          bool     `json:"memory_enabled,omitempty,omitzero"`
	NexusEnabled           bool     `json:"nexus_enabled,omitempty,omitzero"`
	Ok                     bool     `json:"ok"`
	PathModel              string   `json:"path_model,omitempty,omitzero"`
	RuntimeContractVersion int      `json:"runtime_contract_version"`
	Service                string   `json:"service"`
	Source                 string   `json:"source"`
	ToolCount              int      `json:"tool_count,omitempty,omitzero"`
	Tools                  []string `json:"tools,omitempty,omitzero"`
	Version                string   `json:"version"`
}

// TaskCondition defines model for TaskCondition.
type TaskCondition struct {
	CreatedAt string `json:"created_at"`
	ID        string `json:"id"`
	Text      string `json:"text"`
}

// TaskDeleteResponse defines model for TaskDeleteResponse.
type TaskDeleteResponse struct {
	Action      string     `json:"action"`
	DeletedTask JSONObject `json:"deleted_task"`
	Ok          bool       `json:"ok"`
	Source      string     `json:"source"`
	TaskID      string     `json:"task_id"`
}

// TaskDetailResponse defines model for TaskDetailResponse.
type TaskDetailResponse struct {
	Action string    `json:"action"`
	Ok     bool      `json:"ok"`
	Source string    `json:"source"`
	Task   TaskState `json:"task"`
}

// TaskEvent defines model for TaskEvent.
type TaskEvent struct {
	CreatedAt string `json:"created_at"`
	Summary   string `json:"summary"`
	Type      string `json:"type"`
}

// TaskFinalReview defines model for TaskFinalReview.
type TaskFinalReview struct {
	MissingChecks  []string `json:"missing_checks,omitempty,omitzero"`
	OpenRisks      []string `json:"open_risks,omitempty,omitzero"`
	ReviewRevision string   `json:"review_revision"`
	ReviewedAt     string   `json:"reviewed_at"`
	Status         string   `json:"status"`
	Summary        string   `json:"summary"`
	VerifiedFacts  []string `json:"verified_facts,omitempty,omitzero"`
}

// TaskListResponse defines model for TaskListResponse.
type TaskListResponse struct {
	Action string        `json:"action"`
	Count  int           `json:"count"`
	Ok     bool          `json:"ok"`
	Source string        `json:"source"`
	Tasks  []TaskSummary `json:"tasks"`
}

// TaskState defines model for TaskState.
type TaskState struct {
	Blocker       string           `json:"blocker,omitempty,omitzero"`
	CompletedAt   string           `json:"completed_at,omitempty,omitzero"`
	Conditions    []TaskCondition  `json:"conditions"`
	CreatedAt     string           `json:"created_at"`
	Device        string           `json:"device,omitempty,omitzero"`
	Events        []TaskEvent      `json:"events"`
	FinalReview   *TaskFinalReview `json:"final_review,omitempty"`
	Goal          string           `json:"goal"`
	ID            string           `json:"id"`
	Phase         string           `json:"phase"`
	Project       string           `json:"project,omitempty,omitzero"`
	SchemaVersion int              `json:"schema_version"`
	Status        string           `json:"status"`
	Steps         []TaskStep       `json:"steps,omitempty,omitzero"`
	Summary       string           `json:"summary,omitempty,omitzero"`
	Title         string           `json:"title"`
	UpdatedAt     string           `json:"updated_at"`
}

// TaskStep defines model for TaskStep.
type TaskStep struct {
	ID        string `json:"id"`
	Phase     string `json:"phase,omitempty,omitzero"`
	Status    string `json:"status"`
	Title     string `json:"title"`
	UpdatedAt string `json:"updated_at,omitempty,omitzero"`
}

// TaskSummary defines model for TaskSummary.
type TaskSummary struct {
	Blocker            string       `json:"blocker,omitempty,omitzero"`
	CompletedAt        string       `json:"completed_at,omitempty,omitzero"`
	CompletedStepCount int          `json:"completed_step_count"`
	CreatedAt          string       `json:"created_at"`
	CurrentStep        *TaskStep    `json:"current_step,omitempty"`
	EventCount         int          `json:"event_count"`
	Goal               string       `json:"goal"`
	ID                 string       `json:"id"`
	Phase              string       `json:"phase"`
	ReviewStatus       string       `json:"review_status"`
	SourceTemplates    []JSONObject `json:"source_templates,omitempty,omitzero"`
	Status             string       `json:"status"`
	StepCount          int          `json:"step_count"`
	Summary            string       `json:"summary,omitempty,omitzero"`
	Title              string       `json:"title"`
	UpdatedAt          string       `json:"updated_at"`
}

// GetRuntimeSkillParams defines parameters for GetRuntimeSkill.
type GetRuntimeSkillParams struct {
	SkillRef string `form:"skill_ref,omitempty" json:"skill_ref,omitempty,omitzero"`
}

// ListRuntimeSkillFilesParams defines parameters for ListRuntimeSkillFiles.
type ListRuntimeSkillFilesParams struct {
	SkillRef string `form:"skill_ref,omitempty" json:"skill_ref,omitempty,omitzero"`
}

// GetRuntimeSkillFileParams defines parameters for GetRuntimeSkillFile.
type GetRuntimeSkillFileParams struct {
	SkillRef string `form:"skill_ref,omitempty" json:"skill_ref,omitempty,omitzero"`
}

// ListRuntimeTasksParams defines parameters for ListRuntimeTasks.
type ListRuntimeTasksParams struct {
	Status string `form:"status,omitempty" json:"status,omitempty,omitzero"`
	Limit  int    `form:"limit,omitempty" json:"limit,omitempty,omitzero"`
}

// ManageRuntimeMCPJSONRequestBody defines body for ManageRuntimeMCP for application/json ContentType.
type ManageRuntimeMCPJSONRequestBody = JSONObject
